apiVersion: v1
kind: Service
metadata:
  name: etcd-nodeport
  namespace: etcd
spec:
  type: NodePort
  selector:
    app: etcd
  ports:
    - name: client
      port: 2379
      targetPort: 2379
      nodePort: 32379
