# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmonitor.proto\x12\x07monitor\"L\n\x0bMonitorData\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0e\n\x06metric\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\"6\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"J\n\x0f\x43ommandResponse\x12\"\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x14.monitor.MonitorData\x12\x13\n\x0b\x65xec_output\x18\x02 \x01(\t2X\n\x0eMonitorService\x12\x46\n\rCommandStream\x12\x18.monitor.CommandResponse\x1a\x17.monitor.CommandRequest(\x01\x30\x01\x62\x06proto3')



_MONITORDATA = DESCRIPTOR.message_types_by_name['MonitorData']
_COMMANDREQUEST = DESCRIPTOR.message_types_by_name['CommandRequest']
_COMMANDRESPONSE = DESCRIPTOR.message_types_by_name['CommandResponse']
MonitorData = _reflection.GeneratedProtocolMessageType('MonitorData', (_message.Message,), {
  'DESCRIPTOR' : _MONITORDATA,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.MonitorData)
  })
_sym_db.RegisterMessage(MonitorData)

CommandRequest = _reflection.GeneratedProtocolMessageType('CommandRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDREQUEST,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.CommandRequest)
  })
_sym_db.RegisterMessage(CommandRequest)

CommandResponse = _reflection.GeneratedProtocolMessageType('CommandResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDRESPONSE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.CommandResponse)
  })
_sym_db.RegisterMessage(CommandResponse)

_MONITORSERVICE = DESCRIPTOR.services_by_name['MonitorService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MONITORDATA._serialized_start=26
  _MONITORDATA._serialized_end=102
  _COMMANDREQUEST._serialized_start=104
  _COMMANDREQUEST._serialized_end=158
  _COMMANDRESPONSE._serialized_start=160
  _COMMANDRESPONSE._serialized_end=234
  _MONITORSERVICE._serialized_start=236
  _MONITORSERVICE._serialized_end=324
# @@protoc_insertion_point(module_scope)
